// <auto-generated />
using System;
using LenSys.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LenSys.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211020104749_UpdteProprtyFinac")]
    partial class UpdteProprtyFinac
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LenSys.Models.AppAssetFinance.AppAssetFinance", b =>
                {
                    b.Property<int>("AssetFinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssetType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BalloonPayment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Deposit")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LeadId")
                        .HasColumnType("int");

                    b.Property<int>("LoanAmount")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PurchasePriceOfAssetValue")
                        .HasColumnType("int");

                    b.Property<string>("RepaymentTermMonths")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VATincluded")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssetFinId");

                    b.HasIndex("LeadId");

                    b.ToTable("AppAssetFinance");
                });

            modelBuilder.Entity("LenSys.Models.AppAssetFinance.AppAssetFinanceBusniess.AppAssetFinanceBusniess", b =>
                {
                    b.Property<int>("BusniessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AppAssetFinanceAssetFinId")
                        .HasColumnType("int");

                    b.Property<int?>("BusniessDetailsId")
                        .HasColumnType("int");

                    b.HasKey("BusniessId");

                    b.HasIndex("AppAssetFinanceAssetFinId");

                    b.HasIndex("BusniessDetailsId");

                    b.ToTable("AppAssetFinanceBusniess");
                });

            modelBuilder.Entity("LenSys.Models.AppAssetFinance.AppAssetFinanceIndividual.AppAssetFinanceIndividual", b =>
                {
                    b.Property<int>("IndividualId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddressDetailsId")
                        .HasColumnType("int");

                    b.Property<int?>("AppAssetFinanceAssetFinId")
                        .HasColumnType("int");

                    b.Property<int?>("AssetId")
                        .HasColumnType("int");

                    b.Property<int?>("CreditHistoryId")
                        .HasColumnType("int");

                    b.Property<int?>("EmploymentDetailsId")
                        .HasColumnType("int");

                    b.Property<int?>("LiabilitiesId")
                        .HasColumnType("int");

                    b.Property<int?>("MonthlyExpenditureId")
                        .HasColumnType("int");

                    b.Property<int?>("MonthlyIncomeId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonalDetailsId")
                        .HasColumnType("int");

                    b.HasKey("IndividualId");

                    b.HasIndex("AddressDetailsId");

                    b.HasIndex("AppAssetFinanceAssetFinId");

                    b.HasIndex("AssetId");

                    b.HasIndex("CreditHistoryId");

                    b.HasIndex("EmploymentDetailsId");

                    b.HasIndex("LiabilitiesId");

                    b.HasIndex("MonthlyExpenditureId");

                    b.HasIndex("MonthlyIncomeId");

                    b.HasIndex("PersonalDetailsId");

                    b.ToTable("AppAssetFinanceIndividual");
                });

            modelBuilder.Entity("LenSys.Models.AppBusniessFinance.AppBusniessFinance", b =>
                {
                    b.Property<int>("BusniessFinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountantAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountantCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountantEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountantName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccountantPhoneNo")
                        .HasColumnType("int");

                    b.Property<int>("AmountOfFinance")
                        .HasColumnType("int");

                    b.Property<int>("BrokerFee")
                        .HasColumnType("int");

                    b.Property<string>("EverLivedinThisProperty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FCA_RegulatedLoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LeadId")
                        .HasColumnType("int");

                    b.Property<int>("RepaymentTermMonths")
                        .HasColumnType("int");

                    b.Property<string>("SecurityOffered")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfFinance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WillApplicantOrFamilyMemOwn40PercentOfSecurityatmortgageTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BusniessFinId");

                    b.HasIndex("LeadId");

                    b.ToTable("AppBusniessFinance");
                });

            modelBuilder.Entity("LenSys.Models.AppBusniessFinance.AppBusniessFinanceBusniess.AppBusniessFinanceBusniess", b =>
                {
                    b.Property<int>("BusniessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AppBusniessFinanceBusniessFinId")
                        .HasColumnType("int");

                    b.Property<int?>("BusniessDetailsId")
                        .HasColumnType("int");

                    b.HasKey("BusniessId");

                    b.HasIndex("AppBusniessFinanceBusniessFinId");

                    b.HasIndex("BusniessDetailsId");

                    b.ToTable("AppBusniessFinanceBusniess");
                });

            modelBuilder.Entity("LenSys.Models.AppBusniessFinance.AppBusniessFinanceIndividual.AppBusniessFinanceIndividual", b =>
                {
                    b.Property<int>("IndividualId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddressDetailsId")
                        .HasColumnType("int");

                    b.Property<int?>("AppBusniessFinanceBusniessFinId")
                        .HasColumnType("int");

                    b.Property<int?>("AssetId")
                        .HasColumnType("int");

                    b.Property<int?>("CreditHistoryId")
                        .HasColumnType("int");

                    b.Property<int?>("EmploymentDetailsId")
                        .HasColumnType("int");

                    b.Property<int?>("LiabilitiesId")
                        .HasColumnType("int");

                    b.Property<int?>("MonthlyExpenditureId")
                        .HasColumnType("int");

                    b.Property<int?>("MonthlyIncomeId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonalDetailsId")
                        .HasColumnType("int");

                    b.HasKey("IndividualId");

                    b.HasIndex("AddressDetailsId");

                    b.HasIndex("AppBusniessFinanceBusniessFinId");

                    b.HasIndex("AssetId");

                    b.HasIndex("CreditHistoryId");

                    b.HasIndex("EmploymentDetailsId");

                    b.HasIndex("LiabilitiesId");

                    b.HasIndex("MonthlyExpenditureId");

                    b.HasIndex("MonthlyIncomeId");

                    b.HasIndex("PersonalDetailsId");

                    b.ToTable("AppBusniessFinanceIndividual");
                });

            modelBuilder.Entity("LenSys.Models.AppBusniessFinance.AppBusniessFinanceSecurityDetails", b =>
                {
                    b.Property<int>("SecurityDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressForPropertyOfSecurity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AppBusniessFinanceBusniessFinId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegalChargeOverProperty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfPropertyOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OriginalPurchasePrice")
                        .HasColumnType("int");

                    b.Property<int>("PostCode")
                        .HasColumnType("int");

                    b.Property<string>("PropertyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyValue")
                        .HasColumnType("int");

                    b.Property<string>("SecondLineAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tenure")
                        .HasColumnType("int");

                    b.Property<int>("YearsRemainingOnLeaseIfLeaseHold")
                        .HasColumnType("int");

                    b.HasKey("SecurityDetailsId");

                    b.HasIndex("AppBusniessFinanceBusniessFinId");

                    b.ToTable("AppBusniessFinanceSecurityDetails");
                });

            modelBuilder.Entity("LenSys.Models.AppDevelopmentFinance.AppDevelopmentFinance", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Acquistion")
                        .HasColumnType("datetime2");

                    b.Property<int>("AmountOfExistingLoanToBe")
                        .HasColumnType("int");

                    b.Property<DateTime>("BuildingSignOff")
                        .HasColumnType("datetime2");

                    b.Property<int>("CIL")
                        .HasColumnType("int");

                    b.Property<int>("ConstructionCost")
                        .HasColumnType("int");

                    b.Property<int>("Demolition")
                        .HasColumnType("int");

                    b.Property<string>("DetailsOfBuildersContrators")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetailsOfPlainingPermission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ElectricInstallation")
                        .HasColumnType("int");

                    b.Property<int>("EstateAgentFees")
                        .HasColumnType("int");

                    b.Property<string>("EverLivedinThisProperty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExistStrategy")
                        .HasColumnType("int");

                    b.Property<string>("FCA_RegulatedLoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GasInstallation")
                        .HasColumnType("int");

                    b.Property<int>("GrossDevelopmentValue")
                        .HasColumnType("int");

                    b.Property<int>("Insert1")
                        .HasColumnType("int");

                    b.Property<int>("Insert2")
                        .HasColumnType("int");

                    b.Property<int>("Insert3")
                        .HasColumnType("int");

                    b.Property<int>("Insert4")
                        .HasColumnType("int");

                    b.Property<int>("Labour")
                        .HasColumnType("int");

                    b.Property<int>("LandScapingCost")
                        .HasColumnType("int");

                    b.Property<int?>("LeadId")
                        .HasColumnType("int");

                    b.Property<int>("LegalFees")
                        .HasColumnType("int");

                    b.Property<int>("LoanAmount")
                        .HasColumnType("int");

                    b.Property<int>("LoanTermMonths")
                        .HasColumnType("int");

                    b.Property<int>("MarketValueOfLand")
                        .HasColumnType("int");

                    b.Property<int>("MaterialsCost")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OtherCostFinance")
                        .HasColumnType("int");

                    b.Property<DateTime>("PlainingConditions")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PlainingPermission")
                        .HasColumnType("datetime2");

                    b.Property<int>("PurchasePrice")
                        .HasColumnType("int");

                    b.Property<DateTime>("SaleLetWholeBuilding")
                        .HasColumnType("datetime2");

                    b.Property<string>("SellingCosts_Insert1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellingCosts_Insert2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SellingCosts_LegalFees")
                        .HasColumnType("int");

                    b.Property<int>("SellingCosts_Total")
                        .HasColumnType("int");

                    b.Property<int>("SourceOfDeposit")
                        .HasColumnType("int");

                    b.Property<int>("StampDuty")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartConstruction")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TargetCompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalCosts")
                        .HasColumnType("int");

                    b.Property<int>("TotalDevelopmentCost")
                        .HasColumnType("int");

                    b.Property<int>("WaterInstallation")
                        .HasColumnType("int");

                    b.Property<string>("WillApplicantOrFamilyMemOwn40PercentOfSecurityatmortgageTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoanId");

                    b.HasIndex("LeadId");

                    b.ToTable("AppDevelopmentFinance");
                });

            modelBuilder.Entity("LenSys.Models.AppDevelopmentFinance.AppDevelopmentFinanceBusniess.AppDevelopmentFinanceBusniess", b =>
                {
                    b.Property<int>("BusniessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AppDevelopmentFinanceLoanId")
                        .HasColumnType("int");

                    b.Property<int?>("BusniessDetailsId")
                        .HasColumnType("int");

                    b.HasKey("BusniessId");

                    b.HasIndex("AppDevelopmentFinanceLoanId");

                    b.HasIndex("BusniessDetailsId");

                    b.ToTable("AppDevelopmentFinanceBusniess");
                });

            modelBuilder.Entity("LenSys.Models.AppDevelopmentFinance.AppDevelopmentFinanceIndividual.AppDevelopmentFinanceIndividual", b =>
                {
                    b.Property<int>("IndividualId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddressDetailsId")
                        .HasColumnType("int");

                    b.Property<int?>("AppDevelopmentFinanceLoanId")
                        .HasColumnType("int");

                    b.Property<int?>("AssetId")
                        .HasColumnType("int");

                    b.Property<int?>("CreditHistoryId")
                        .HasColumnType("int");

                    b.Property<int?>("EmploymentDetailsId")
                        .HasColumnType("int");

                    b.Property<int?>("LiabilitiesId")
                        .HasColumnType("int");

                    b.Property<int?>("MonthlyExpenditureId")
                        .HasColumnType("int");

                    b.Property<int?>("MonthlyIncomeId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonalDetailsId")
                        .HasColumnType("int");

                    b.HasKey("IndividualId");

                    b.HasIndex("AddressDetailsId");

                    b.HasIndex("AppDevelopmentFinanceLoanId");

                    b.HasIndex("AssetId");

                    b.HasIndex("CreditHistoryId");

                    b.HasIndex("EmploymentDetailsId");

                    b.HasIndex("LiabilitiesId");

                    b.HasIndex("MonthlyExpenditureId");

                    b.HasIndex("MonthlyIncomeId");

                    b.HasIndex("PersonalDetailsId");

                    b.ToTable("AppDevelopmentFinanceIndividual");
                });

            modelBuilder.Entity("LenSys.Models.AppDevelopmentFinance.AppDevelopmentFinanceSecurityDetails", b =>
                {
                    b.Property<int>("SecurityDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressForPropertyOfSecurity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AppDevelopmentFinanceLoanId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionOfProperty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfPropertyOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostCode")
                        .HasColumnType("int");

                    b.Property<string>("PropertyCurrentUse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondLineAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tenure")
                        .HasColumnType("int");

                    b.Property<int>("YearsRemainingOnLeaseIfLeaseHold")
                        .HasColumnType("int");

                    b.HasKey("SecurityDetailsId");

                    b.HasIndex("AppDevelopmentFinanceLoanId");

                    b.ToTable("AppDevelopmentFinanceSecurityDetails");
                });

            modelBuilder.Entity("LenSys.Models.AppPropertyFinance.AppPropertyFinance", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountantAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountantCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountantEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountantName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccountantPhoneNo")
                        .HasColumnType("int");

                    b.Property<int>("BrokerFee")
                        .HasColumnType("int");

                    b.Property<string>("EverLivedinThisProperty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FCA_RegulatedLoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LeadId")
                        .HasColumnType("int");

                    b.Property<int>("LoanAmount")
                        .HasColumnType("int");

                    b.Property<string>("LoanPurpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RateType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RepaymentTermMonths")
                        .HasColumnType("int");

                    b.Property<string>("RepaymentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolicitorAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolicitorCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SolicitorDXnumber")
                        .HasColumnType("int");

                    b.Property<string>("SolicitorEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolicitorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SolicitorPhoneNo")
                        .HasColumnType("int");

                    b.Property<int>("SourceOfDeposit")
                        .HasColumnType("int");

                    b.Property<DateTime>("TargetCompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("WillApplicantOrFamilyMemOwn40PercentOfSecurityatmortgageTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoanId");

                    b.HasIndex("LeadId");

                    b.ToTable("AppPropertyFinance");
                });

            modelBuilder.Entity("LenSys.Models.AppPropertyFinance.AppPropertyFinanceBusniess.AppPropertyFinanceBusniess", b =>
                {
                    b.Property<int>("BusniessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AppPropertyFinanceLoanId")
                        .HasColumnType("int");

                    b.Property<int?>("BusniessDetailsId")
                        .HasColumnType("int");

                    b.HasKey("BusniessId");

                    b.HasIndex("AppPropertyFinanceLoanId");

                    b.HasIndex("BusniessDetailsId");

                    b.ToTable("AppPropertyFinanceBusniess");
                });

            modelBuilder.Entity("LenSys.Models.AppPropertyFinance.AppPropertyFinanceIndividual.AppPropertyFinanceIndividual", b =>
                {
                    b.Property<int>("IndividualId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddressDetailsId")
                        .HasColumnType("int");

                    b.Property<int?>("AppPropertyFinanceLoanId")
                        .HasColumnType("int");

                    b.Property<int?>("AssetId")
                        .HasColumnType("int");

                    b.Property<int?>("CreditHistoryId")
                        .HasColumnType("int");

                    b.Property<int?>("EmploymentDetailsId")
                        .HasColumnType("int");

                    b.Property<int?>("LiabilitiesId")
                        .HasColumnType("int");

                    b.Property<int?>("MonthlyExpenditureId")
                        .HasColumnType("int");

                    b.Property<int?>("MonthlyIncomeId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonalDetailsId")
                        .HasColumnType("int");

                    b.HasKey("IndividualId");

                    b.HasIndex("AddressDetailsId");

                    b.HasIndex("AppPropertyFinanceLoanId");

                    b.HasIndex("AssetId");

                    b.HasIndex("CreditHistoryId");

                    b.HasIndex("EmploymentDetailsId");

                    b.HasIndex("LiabilitiesId");

                    b.HasIndex("MonthlyExpenditureId");

                    b.HasIndex("MonthlyIncomeId");

                    b.HasIndex("PersonalDetailsId");

                    b.ToTable("AppPropertyFinanceIndividual");
                });

            modelBuilder.Entity("LenSys.Models.AppPropertyFinance.AppPropertyFinanceSecurityDetails", b =>
                {
                    b.Property<int>("SecurityDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressForPropertyOfSecurity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlreadyOwned")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AppPropertyFinanceLoanId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HMO_MUFB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfPropertyOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OriginalPurchasePrice")
                        .HasColumnType("int");

                    b.Property<int>("PostCode")
                        .HasColumnType("int");

                    b.Property<string>("PropertyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyValue")
                        .HasColumnType("int");

                    b.Property<int>("Rent")
                        .HasColumnType("int");

                    b.Property<string>("SecondLineAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tenure")
                        .HasColumnType("int");

                    b.Property<string>("UseOfFunds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearsRemainingOnLeaseIfLeaseHold")
                        .HasColumnType("int");

                    b.HasKey("SecurityDetailsId");

                    b.HasIndex("AppPropertyFinanceLoanId");

                    b.ToTable("AppPropertyFinanceSecurityDetails");
                });

            modelBuilder.Entity("LenSys.Models.BusniessDetails.BusniessDetails", b =>
                {
                    b.Property<int>("BusniessDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyBusniessName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrespondenceAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NatureOfBusniess")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegisteredAddress")
                        .HasColumnType("int");

                    b.Property<int>("RegisteredNumber")
                        .HasColumnType("int");

                    b.Property<string>("TradingAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TradingSince")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BusniessDetailsId");

                    b.ToTable("BusniessDetails");
                });

            modelBuilder.Entity("LenSys.Models.BusniessKeyPrincipals.KeyPrincipals", b =>
                {
                    b.Property<int>("KeyPrincipalsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AppAssetFinanceBusniessBusniessId")
                        .HasColumnType("int");

                    b.Property<int?>("AppBusniessFinanceBusniessBusniessId")
                        .HasColumnType("int");

                    b.Property<int?>("AppDevelopmentFinanceBusniessBusniessId")
                        .HasColumnType("int");

                    b.Property<int?>("AppPropertyFinanceBusniessBusniessId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PercentageShareholding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KeyPrincipalsId");

                    b.HasIndex("AppAssetFinanceBusniessBusniessId");

                    b.HasIndex("AppBusniessFinanceBusniessBusniessId");

                    b.HasIndex("AppDevelopmentFinanceBusniessBusniessId");

                    b.HasIndex("AppPropertyFinanceBusniessBusniessId");

                    b.ToTable("KeyPrincipals");
                });

            modelBuilder.Entity("LenSys.Models.BusniessLiabilities.BusniessLiabilities", b =>
                {
                    b.Property<int>("BusniessLiabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AppAssetFinanceBusniessBusniessId")
                        .HasColumnType("int");

                    b.Property<int?>("AppBusniessFinanceBusniessBusniessId")
                        .HasColumnType("int");

                    b.Property<int?>("AppDevelopmentFinanceBusniessBusniessId")
                        .HasColumnType("int");

                    b.Property<int?>("AppPropertyFinanceBusniessBusniessId")
                        .HasColumnType("int");

                    b.Property<int>("CommitmentTerm")
                        .HasColumnType("int");

                    b.Property<int>("EarlyRepaymentCharge")
                        .HasColumnType("int");

                    b.Property<string>("FixedOrVariable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FixedTerm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InitialTerm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonthlyPayment")
                        .HasColumnType("int");

                    b.Property<int>("OrigionalLoanAmount")
                        .HasColumnType("int");

                    b.Property<int>("OutstandingBalance")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<string>("RemainingTerm")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BusniessLiabilityId");

                    b.HasIndex("AppAssetFinanceBusniessBusniessId");

                    b.HasIndex("AppBusniessFinanceBusniessBusniessId");

                    b.HasIndex("AppDevelopmentFinanceBusniessBusniessId");

                    b.HasIndex("AppPropertyFinanceBusniessBusniessId");

                    b.ToTable("BusniessLiabilities");
                });

            modelBuilder.Entity("LenSys.Models.BusniessServiceability.Serviceability", b =>
                {
                    b.Property<int>("ServiceabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AppAssetFinanceBusniessBusniessId")
                        .HasColumnType("int");

                    b.Property<int?>("AppBusniessFinanceBusniessBusniessId")
                        .HasColumnType("int");

                    b.Property<int?>("AppDevelopmentFinanceBusniessBusniessId")
                        .HasColumnType("int");

                    b.Property<int?>("AppPropertyFinanceBusniessBusniessId")
                        .HasColumnType("int");

                    b.Property<string>("EBITDA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NetProfit")
                        .HasColumnType("int");

                    b.Property<int>("TurnOver")
                        .HasColumnType("int");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServiceabilityId");

                    b.HasIndex("AppAssetFinanceBusniessBusniessId");

                    b.HasIndex("AppBusniessFinanceBusniessBusniessId");

                    b.HasIndex("AppDevelopmentFinanceBusniessBusniessId");

                    b.HasIndex("AppPropertyFinanceBusniessBusniessId");

                    b.ToTable("Serviceability");
                });

            modelBuilder.Entity("LenSys.Models.BusniessUploadDocument.BusniessDocuments", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AppAssetFinanceBusniessBusniessId")
                        .HasColumnType("int");

                    b.Property<int?>("AppBusniessFinanceBusniessBusniessId")
                        .HasColumnType("int");

                    b.Property<int?>("AppDevelopmentFinanceBusniessBusniessId")
                        .HasColumnType("int");

                    b.Property<int>("AppId")
                        .HasColumnType("int");

                    b.Property<int?>("AppPropertyFinanceBusniessBusniessId")
                        .HasColumnType("int");

                    b.Property<int>("BusniessId")
                        .HasColumnType("int");

                    b.Property<int>("DocumentGuid")
                        .HasColumnType("int");

                    b.Property<string>("DocumentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentId");

                    b.HasIndex("AppAssetFinanceBusniessBusniessId");

                    b.HasIndex("AppBusniessFinanceBusniessBusniessId");

                    b.HasIndex("AppDevelopmentFinanceBusniessBusniessId");

                    b.HasIndex("AppPropertyFinanceBusniessBusniessId");

                    b.ToTable("BusniessDocuments");
                });

            modelBuilder.Entity("LenSys.Models.Home.Lead", b =>
                {
                    b.Property<int>("LeadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyBusniessName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntroducerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoanAmount")
                        .HasColumnType("int");

                    b.Property<string>("LoanPurpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNo")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeadId");

                    b.ToTable("Lead");
                });

            modelBuilder.Entity("LenSys.Models.IndividualAddressDetails.AddressDetails", b =>
                {
                    b.Property<int>("AddressDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateMovedIn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstLineAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LessThanThreeYears")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MarketValue")
                        .HasColumnType("int");

                    b.Property<int>("OutstandingMortgageBalance")
                        .HasColumnType("int");

                    b.Property<int>("PostCode")
                        .HasColumnType("int");

                    b.Property<string>("PreviousCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PreviousDateMovedIn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PreviousFirstLineAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PreviousPostCode")
                        .HasColumnType("int");

                    b.Property<string>("PreviousSecondLineAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResidentialStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondLineAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressDetailsId");

                    b.ToTable("AddressDetails");
                });

            modelBuilder.Entity("LenSys.Models.IndividualAsset.Asset", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cash")
                        .HasColumnType("int");

                    b.Property<int>("LifePolicy")
                        .HasColumnType("int");

                    b.Property<int>("OtherInvestments")
                        .HasColumnType("int");

                    b.Property<int>("PersonalDewellingHouse")
                        .HasColumnType("int");

                    b.Property<int>("Shares")
                        .HasColumnType("int");

                    b.Property<int>("TotalAssets")
                        .HasColumnType("int");

                    b.HasKey("AssetId");

                    b.ToTable("Asset");
                });

            modelBuilder.Entity("LenSys.Models.IndividualCreditHistory.CreditHistory", b =>
                {
                    b.Property<int>("CreditHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CriminalConvictions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeclaredBankrupt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuarantorOnLoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IVAorCVA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegalAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalCreditRating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyRepossessed")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CreditHistoryId");

                    b.ToTable("CreditHistory");
                });

            modelBuilder.Entity("LenSys.Models.IndividualEmploymentDetails.EmploymentDetails", b =>
                {
                    b.Property<int>("EmploymentDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmployersName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmploymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmploymentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GrossSalary")
                        .HasColumnType("int");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LatestEarnedIncomeYearOne")
                        .HasColumnType("int");

                    b.Property<int>("LatestEarnedIncomeYearThree")
                        .HasColumnType("int");

                    b.Property<int>("LatestEarnedIncomeYearTwo")
                        .HasColumnType("int");

                    b.Property<int>("NationalInsuranceNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EmploymentDetailsId");

                    b.ToTable("EmploymentDetails");
                });

            modelBuilder.Entity("LenSys.Models.IndividualIncomeExpenditure.MonthlyIncome", b =>
                {
                    b.Property<int>("MonthlyIncomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DividendsAfterTax")
                        .HasColumnType("int");

                    b.Property<int>("OtherIncomeInvestments")
                        .HasColumnType("int");

                    b.Property<int>("PartnerEaningAfterTax")
                        .HasColumnType("int");

                    b.Property<int>("SalaryAfterTax")
                        .HasColumnType("int");

                    b.Property<int>("TotalIncome")
                        .HasColumnType("int");

                    b.HasKey("MonthlyIncomeId");

                    b.ToTable("MonthlyIncome");
                });

            modelBuilder.Entity("LenSys.Models.IndividualLiabilities.Liabilities", b =>
                {
                    b.Property<int>("LiabilitiesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarLoanHP")
                        .HasColumnType("int");

                    b.Property<int>("NetAssets")
                        .HasColumnType("int");

                    b.Property<int>("Others")
                        .HasColumnType("int");

                    b.Property<int>("Overdraft")
                        .HasColumnType("int");

                    b.Property<int>("PersonalGuaranteesSigned")
                        .HasColumnType("int");

                    b.Property<int>("PersonalLoan1")
                        .HasColumnType("int");

                    b.Property<int>("PersonalLoan2")
                        .HasColumnType("int");

                    b.Property<int>("PersonalLoan3")
                        .HasColumnType("int");

                    b.Property<int>("ResidentialMortgage")
                        .HasColumnType("int");

                    b.Property<int>("StoreCreditCard1")
                        .HasColumnType("int");

                    b.Property<int>("StoreCreditCard2")
                        .HasColumnType("int");

                    b.Property<int>("StoreCreditCard3")
                        .HasColumnType("int");

                    b.Property<int>("TotalLiabilities")
                        .HasColumnType("int");

                    b.HasKey("LiabilitiesId");

                    b.ToTable("Liabilities");
                });

            modelBuilder.Entity("LenSys.Models.IndividualMonthlyExpenditure.MonthlyExpenditure", b =>
                {
                    b.Property<int>("MonthlyExpenditureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarInsuranceRoadTax")
                        .HasColumnType("int");

                    b.Property<int>("EntertainmentSubscriptions")
                        .HasColumnType("int");

                    b.Property<int>("FoodAndClothing")
                        .HasColumnType("int");

                    b.Property<int>("HomeBuildingContentsInsurance")
                        .HasColumnType("int");

                    b.Property<int>("LifeAssurancePension")
                        .HasColumnType("int");

                    b.Property<int>("LoanHPCreditCardPayments")
                        .HasColumnType("int");

                    b.Property<int>("MonthlyDisposableIncome")
                        .HasColumnType("int");

                    b.Property<int>("MortgageRent")
                        .HasColumnType("int");

                    b.Property<int>("OtherCostChristmisHolidays")
                        .HasColumnType("int");

                    b.Property<int>("PetrolCarMaintenance")
                        .HasColumnType("int");

                    b.Property<int>("RatesCouncilTax")
                        .HasColumnType("int");

                    b.Property<int>("TotalExpenditure")
                        .HasColumnType("int");

                    b.Property<int>("TravelToWork")
                        .HasColumnType("int");

                    b.Property<int>("WaterGasElectricityTelephoneBill")
                        .HasColumnType("int");

                    b.HasKey("MonthlyExpenditureId");

                    b.ToTable("MonthlyExpenditure");
                });

            modelBuilder.Entity("LenSys.Models.IndividualPersonalDetails.PersonalDetails", b =>
                {
                    b.Property<int>("PersonalDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LengthOfResidencyYears")
                        .HasColumnType("int");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nationality")
                        .HasColumnType("int");

                    b.Property<string>("PermanentRightForUkResident")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNo")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonalDetailsId");

                    b.ToTable("PersonalDetails");
                });

            modelBuilder.Entity("LenSys.Models.IndividualPropertySchedule.PropertySchedule", b =>
                {
                    b.Property<int>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AppAssetFinanceIndividualIndividualId")
                        .HasColumnType("int");

                    b.Property<int?>("AppBusniessFinanceIndividualIndividualId")
                        .HasColumnType("int");

                    b.Property<int?>("AppDevelopmentFinanceIndividualIndividualId")
                        .HasColumnType("int");

                    b.Property<int?>("AppPropertyFinanceIndividualIndividualId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentMarketValue")
                        .HasColumnType("int");

                    b.Property<int>("InterestRate")
                        .HasColumnType("int");

                    b.Property<string>("LTV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MortgagePcm")
                        .HasColumnType("int");

                    b.Property<int>("OrigionalMortgageAmount")
                        .HasColumnType("int");

                    b.Property<int>("OutstandingMortgage")
                        .HasColumnType("int");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PurchasePrice")
                        .HasColumnType("int");

                    b.Property<int>("RemainingTerm")
                        .HasColumnType("int");

                    b.Property<int>("RemainingTermOfLease")
                        .HasColumnType("int");

                    b.Property<int>("RentPcm")
                        .HasColumnType("int");

                    b.Property<string>("TypeOfRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfTenancyLeaseASTBoth")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PropertyId");

                    b.HasIndex("AppAssetFinanceIndividualIndividualId");

                    b.HasIndex("AppBusniessFinanceIndividualIndividualId");

                    b.HasIndex("AppDevelopmentFinanceIndividualIndividualId");

                    b.HasIndex("AppPropertyFinanceIndividualIndividualId");

                    b.ToTable("PropertySchedule");
                });

            modelBuilder.Entity("LenSys.Models.IndividualUploadDocuments.IndividualDocuments", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AppAssetFinanceIndividualIndividualId")
                        .HasColumnType("int");

                    b.Property<int?>("AppBusniessFinanceIndividualIndividualId")
                        .HasColumnType("int");

                    b.Property<int?>("AppDevelopmentFinanceIndividualIndividualId")
                        .HasColumnType("int");

                    b.Property<int>("AppId")
                        .HasColumnType("int");

                    b.Property<int?>("AppPropertyFinanceIndividualIndividualId")
                        .HasColumnType("int");

                    b.Property<int>("DocumentGuid")
                        .HasColumnType("int");

                    b.Property<string>("DocumentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IndividualId")
                        .HasColumnType("int");

                    b.HasKey("DocumentId");

                    b.HasIndex("AppAssetFinanceIndividualIndividualId");

                    b.HasIndex("AppBusniessFinanceIndividualIndividualId");

                    b.HasIndex("AppDevelopmentFinanceIndividualIndividualId");

                    b.HasIndex("AppPropertyFinanceIndividualIndividualId");

                    b.ToTable("IndividualDocuments");
                });

            modelBuilder.Entity("LenSys.Models.AppAssetFinance.AppAssetFinance", b =>
                {
                    b.HasOne("LenSys.Models.Home.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("LenSys.Models.AppAssetFinance.AppAssetFinanceBusniess.AppAssetFinanceBusniess", b =>
                {
                    b.HasOne("LenSys.Models.AppAssetFinance.AppAssetFinance", null)
                        .WithMany("busniesses")
                        .HasForeignKey("AppAssetFinanceAssetFinId");

                    b.HasOne("LenSys.Models.BusniessDetails.BusniessDetails", "busniessDetails")
                        .WithMany()
                        .HasForeignKey("BusniessDetailsId");

                    b.Navigation("busniessDetails");
                });

            modelBuilder.Entity("LenSys.Models.AppAssetFinance.AppAssetFinanceIndividual.AppAssetFinanceIndividual", b =>
                {
                    b.HasOne("LenSys.Models.IndividualAddressDetails.AddressDetails", "addressDetails")
                        .WithMany()
                        .HasForeignKey("AddressDetailsId");

                    b.HasOne("LenSys.Models.AppAssetFinance.AppAssetFinance", null)
                        .WithMany("individuals")
                        .HasForeignKey("AppAssetFinanceAssetFinId");

                    b.HasOne("LenSys.Models.IndividualAsset.Asset", "asset")
                        .WithMany()
                        .HasForeignKey("AssetId");

                    b.HasOne("LenSys.Models.IndividualCreditHistory.CreditHistory", "creditHistory")
                        .WithMany()
                        .HasForeignKey("CreditHistoryId");

                    b.HasOne("LenSys.Models.IndividualEmploymentDetails.EmploymentDetails", "employmentDetails")
                        .WithMany()
                        .HasForeignKey("EmploymentDetailsId");

                    b.HasOne("LenSys.Models.IndividualLiabilities.Liabilities", "liabilities")
                        .WithMany()
                        .HasForeignKey("LiabilitiesId");

                    b.HasOne("LenSys.Models.IndividualMonthlyExpenditure.MonthlyExpenditure", "monthlyExpenditure")
                        .WithMany()
                        .HasForeignKey("MonthlyExpenditureId");

                    b.HasOne("LenSys.Models.IndividualIncomeExpenditure.MonthlyIncome", "monthlyIncome")
                        .WithMany()
                        .HasForeignKey("MonthlyIncomeId");

                    b.HasOne("LenSys.Models.IndividualPersonalDetails.PersonalDetails", "personalDetails")
                        .WithMany()
                        .HasForeignKey("PersonalDetailsId");

                    b.Navigation("addressDetails");

                    b.Navigation("asset");

                    b.Navigation("creditHistory");

                    b.Navigation("employmentDetails");

                    b.Navigation("liabilities");

                    b.Navigation("monthlyExpenditure");

                    b.Navigation("monthlyIncome");

                    b.Navigation("personalDetails");
                });

            modelBuilder.Entity("LenSys.Models.AppBusniessFinance.AppBusniessFinance", b =>
                {
                    b.HasOne("LenSys.Models.Home.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("LenSys.Models.AppBusniessFinance.AppBusniessFinanceBusniess.AppBusniessFinanceBusniess", b =>
                {
                    b.HasOne("LenSys.Models.AppBusniessFinance.AppBusniessFinance", null)
                        .WithMany("busniesses")
                        .HasForeignKey("AppBusniessFinanceBusniessFinId");

                    b.HasOne("LenSys.Models.BusniessDetails.BusniessDetails", "busniessDetails")
                        .WithMany()
                        .HasForeignKey("BusniessDetailsId");

                    b.Navigation("busniessDetails");
                });

            modelBuilder.Entity("LenSys.Models.AppBusniessFinance.AppBusniessFinanceIndividual.AppBusniessFinanceIndividual", b =>
                {
                    b.HasOne("LenSys.Models.IndividualAddressDetails.AddressDetails", "addressDetails")
                        .WithMany()
                        .HasForeignKey("AddressDetailsId");

                    b.HasOne("LenSys.Models.AppBusniessFinance.AppBusniessFinance", null)
                        .WithMany("individuals")
                        .HasForeignKey("AppBusniessFinanceBusniessFinId");

                    b.HasOne("LenSys.Models.IndividualAsset.Asset", "asset")
                        .WithMany()
                        .HasForeignKey("AssetId");

                    b.HasOne("LenSys.Models.IndividualCreditHistory.CreditHistory", "creditHistory")
                        .WithMany()
                        .HasForeignKey("CreditHistoryId");

                    b.HasOne("LenSys.Models.IndividualEmploymentDetails.EmploymentDetails", "employmentDetails")
                        .WithMany()
                        .HasForeignKey("EmploymentDetailsId");

                    b.HasOne("LenSys.Models.IndividualLiabilities.Liabilities", "liabilities")
                        .WithMany()
                        .HasForeignKey("LiabilitiesId");

                    b.HasOne("LenSys.Models.IndividualMonthlyExpenditure.MonthlyExpenditure", "monthlyExpenditure")
                        .WithMany()
                        .HasForeignKey("MonthlyExpenditureId");

                    b.HasOne("LenSys.Models.IndividualIncomeExpenditure.MonthlyIncome", "monthlyIncome")
                        .WithMany()
                        .HasForeignKey("MonthlyIncomeId");

                    b.HasOne("LenSys.Models.IndividualPersonalDetails.PersonalDetails", "personalDetails")
                        .WithMany()
                        .HasForeignKey("PersonalDetailsId");

                    b.Navigation("addressDetails");

                    b.Navigation("asset");

                    b.Navigation("creditHistory");

                    b.Navigation("employmentDetails");

                    b.Navigation("liabilities");

                    b.Navigation("monthlyExpenditure");

                    b.Navigation("monthlyIncome");

                    b.Navigation("personalDetails");
                });

            modelBuilder.Entity("LenSys.Models.AppBusniessFinance.AppBusniessFinanceSecurityDetails", b =>
                {
                    b.HasOne("LenSys.Models.AppBusniessFinance.AppBusniessFinance", null)
                        .WithMany("securityDetails")
                        .HasForeignKey("AppBusniessFinanceBusniessFinId");
                });

            modelBuilder.Entity("LenSys.Models.AppDevelopmentFinance.AppDevelopmentFinance", b =>
                {
                    b.HasOne("LenSys.Models.Home.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("LenSys.Models.AppDevelopmentFinance.AppDevelopmentFinanceBusniess.AppDevelopmentFinanceBusniess", b =>
                {
                    b.HasOne("LenSys.Models.AppDevelopmentFinance.AppDevelopmentFinance", null)
                        .WithMany("busniesses")
                        .HasForeignKey("AppDevelopmentFinanceLoanId");

                    b.HasOne("LenSys.Models.BusniessDetails.BusniessDetails", "busniessDetails")
                        .WithMany()
                        .HasForeignKey("BusniessDetailsId");

                    b.Navigation("busniessDetails");
                });

            modelBuilder.Entity("LenSys.Models.AppDevelopmentFinance.AppDevelopmentFinanceIndividual.AppDevelopmentFinanceIndividual", b =>
                {
                    b.HasOne("LenSys.Models.IndividualAddressDetails.AddressDetails", "addressDetails")
                        .WithMany()
                        .HasForeignKey("AddressDetailsId");

                    b.HasOne("LenSys.Models.AppDevelopmentFinance.AppDevelopmentFinance", null)
                        .WithMany("individuals")
                        .HasForeignKey("AppDevelopmentFinanceLoanId");

                    b.HasOne("LenSys.Models.IndividualAsset.Asset", "asset")
                        .WithMany()
                        .HasForeignKey("AssetId");

                    b.HasOne("LenSys.Models.IndividualCreditHistory.CreditHistory", "creditHistory")
                        .WithMany()
                        .HasForeignKey("CreditHistoryId");

                    b.HasOne("LenSys.Models.IndividualEmploymentDetails.EmploymentDetails", "employmentDetails")
                        .WithMany()
                        .HasForeignKey("EmploymentDetailsId");

                    b.HasOne("LenSys.Models.IndividualLiabilities.Liabilities", "liabilities")
                        .WithMany()
                        .HasForeignKey("LiabilitiesId");

                    b.HasOne("LenSys.Models.IndividualMonthlyExpenditure.MonthlyExpenditure", "monthlyExpenditure")
                        .WithMany()
                        .HasForeignKey("MonthlyExpenditureId");

                    b.HasOne("LenSys.Models.IndividualIncomeExpenditure.MonthlyIncome", "monthlyIncome")
                        .WithMany()
                        .HasForeignKey("MonthlyIncomeId");

                    b.HasOne("LenSys.Models.IndividualPersonalDetails.PersonalDetails", "personalDetails")
                        .WithMany()
                        .HasForeignKey("PersonalDetailsId");

                    b.Navigation("addressDetails");

                    b.Navigation("asset");

                    b.Navigation("creditHistory");

                    b.Navigation("employmentDetails");

                    b.Navigation("liabilities");

                    b.Navigation("monthlyExpenditure");

                    b.Navigation("monthlyIncome");

                    b.Navigation("personalDetails");
                });

            modelBuilder.Entity("LenSys.Models.AppDevelopmentFinance.AppDevelopmentFinanceSecurityDetails", b =>
                {
                    b.HasOne("LenSys.Models.AppDevelopmentFinance.AppDevelopmentFinance", null)
                        .WithMany("securityDetails")
                        .HasForeignKey("AppDevelopmentFinanceLoanId");
                });

            modelBuilder.Entity("LenSys.Models.AppPropertyFinance.AppPropertyFinance", b =>
                {
                    b.HasOne("LenSys.Models.Home.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("LenSys.Models.AppPropertyFinance.AppPropertyFinanceBusniess.AppPropertyFinanceBusniess", b =>
                {
                    b.HasOne("LenSys.Models.AppPropertyFinance.AppPropertyFinance", null)
                        .WithMany("busniesses")
                        .HasForeignKey("AppPropertyFinanceLoanId");

                    b.HasOne("LenSys.Models.BusniessDetails.BusniessDetails", "busniessDetails")
                        .WithMany()
                        .HasForeignKey("BusniessDetailsId");

                    b.Navigation("busniessDetails");
                });

            modelBuilder.Entity("LenSys.Models.AppPropertyFinance.AppPropertyFinanceIndividual.AppPropertyFinanceIndividual", b =>
                {
                    b.HasOne("LenSys.Models.IndividualAddressDetails.AddressDetails", "addressDetails")
                        .WithMany()
                        .HasForeignKey("AddressDetailsId");

                    b.HasOne("LenSys.Models.AppPropertyFinance.AppPropertyFinance", null)
                        .WithMany("individuals")
                        .HasForeignKey("AppPropertyFinanceLoanId");

                    b.HasOne("LenSys.Models.IndividualAsset.Asset", "asset")
                        .WithMany()
                        .HasForeignKey("AssetId");

                    b.HasOne("LenSys.Models.IndividualCreditHistory.CreditHistory", "creditHistory")
                        .WithMany()
                        .HasForeignKey("CreditHistoryId");

                    b.HasOne("LenSys.Models.IndividualEmploymentDetails.EmploymentDetails", "employmentDetails")
                        .WithMany()
                        .HasForeignKey("EmploymentDetailsId");

                    b.HasOne("LenSys.Models.IndividualLiabilities.Liabilities", "liabilities")
                        .WithMany()
                        .HasForeignKey("LiabilitiesId");

                    b.HasOne("LenSys.Models.IndividualMonthlyExpenditure.MonthlyExpenditure", "monthlyExpenditure")
                        .WithMany()
                        .HasForeignKey("MonthlyExpenditureId");

                    b.HasOne("LenSys.Models.IndividualIncomeExpenditure.MonthlyIncome", "monthlyIncome")
                        .WithMany()
                        .HasForeignKey("MonthlyIncomeId");

                    b.HasOne("LenSys.Models.IndividualPersonalDetails.PersonalDetails", "personalDetails")
                        .WithMany()
                        .HasForeignKey("PersonalDetailsId");

                    b.Navigation("addressDetails");

                    b.Navigation("asset");

                    b.Navigation("creditHistory");

                    b.Navigation("employmentDetails");

                    b.Navigation("liabilities");

                    b.Navigation("monthlyExpenditure");

                    b.Navigation("monthlyIncome");

                    b.Navigation("personalDetails");
                });

            modelBuilder.Entity("LenSys.Models.AppPropertyFinance.AppPropertyFinanceSecurityDetails", b =>
                {
                    b.HasOne("LenSys.Models.AppPropertyFinance.AppPropertyFinance", null)
                        .WithMany("securityDetails")
                        .HasForeignKey("AppPropertyFinanceLoanId");
                });

            modelBuilder.Entity("LenSys.Models.BusniessKeyPrincipals.KeyPrincipals", b =>
                {
                    b.HasOne("LenSys.Models.AppAssetFinance.AppAssetFinanceBusniess.AppAssetFinanceBusniess", null)
                        .WithMany("keyPrincipals")
                        .HasForeignKey("AppAssetFinanceBusniessBusniessId");

                    b.HasOne("LenSys.Models.AppBusniessFinance.AppBusniessFinanceBusniess.AppBusniessFinanceBusniess", null)
                        .WithMany("keyPrincipals")
                        .HasForeignKey("AppBusniessFinanceBusniessBusniessId");

                    b.HasOne("LenSys.Models.AppDevelopmentFinance.AppDevelopmentFinanceBusniess.AppDevelopmentFinanceBusniess", null)
                        .WithMany("keyPrincipals")
                        .HasForeignKey("AppDevelopmentFinanceBusniessBusniessId");

                    b.HasOne("LenSys.Models.AppPropertyFinance.AppPropertyFinanceBusniess.AppPropertyFinanceBusniess", null)
                        .WithMany("keyPrincipals")
                        .HasForeignKey("AppPropertyFinanceBusniessBusniessId");
                });

            modelBuilder.Entity("LenSys.Models.BusniessLiabilities.BusniessLiabilities", b =>
                {
                    b.HasOne("LenSys.Models.AppAssetFinance.AppAssetFinanceBusniess.AppAssetFinanceBusniess", null)
                        .WithMany("busniessLiabilities")
                        .HasForeignKey("AppAssetFinanceBusniessBusniessId");

                    b.HasOne("LenSys.Models.AppBusniessFinance.AppBusniessFinanceBusniess.AppBusniessFinanceBusniess", null)
                        .WithMany("busniessLiabilities")
                        .HasForeignKey("AppBusniessFinanceBusniessBusniessId");

                    b.HasOne("LenSys.Models.AppDevelopmentFinance.AppDevelopmentFinanceBusniess.AppDevelopmentFinanceBusniess", null)
                        .WithMany("busniessLiabilities")
                        .HasForeignKey("AppDevelopmentFinanceBusniessBusniessId");

                    b.HasOne("LenSys.Models.AppPropertyFinance.AppPropertyFinanceBusniess.AppPropertyFinanceBusniess", null)
                        .WithMany("busniessLiabilities")
                        .HasForeignKey("AppPropertyFinanceBusniessBusniessId");
                });

            modelBuilder.Entity("LenSys.Models.BusniessServiceability.Serviceability", b =>
                {
                    b.HasOne("LenSys.Models.AppAssetFinance.AppAssetFinanceBusniess.AppAssetFinanceBusniess", null)
                        .WithMany("serviceability")
                        .HasForeignKey("AppAssetFinanceBusniessBusniessId");

                    b.HasOne("LenSys.Models.AppBusniessFinance.AppBusniessFinanceBusniess.AppBusniessFinanceBusniess", null)
                        .WithMany("serviceability")
                        .HasForeignKey("AppBusniessFinanceBusniessBusniessId");

                    b.HasOne("LenSys.Models.AppDevelopmentFinance.AppDevelopmentFinanceBusniess.AppDevelopmentFinanceBusniess", null)
                        .WithMany("serviceability")
                        .HasForeignKey("AppDevelopmentFinanceBusniessBusniessId");

                    b.HasOne("LenSys.Models.AppPropertyFinance.AppPropertyFinanceBusniess.AppPropertyFinanceBusniess", null)
                        .WithMany("serviceability")
                        .HasForeignKey("AppPropertyFinanceBusniessBusniessId");
                });

            modelBuilder.Entity("LenSys.Models.BusniessUploadDocument.BusniessDocuments", b =>
                {
                    b.HasOne("LenSys.Models.AppAssetFinance.AppAssetFinanceBusniess.AppAssetFinanceBusniess", null)
                        .WithMany("busniessDocuments")
                        .HasForeignKey("AppAssetFinanceBusniessBusniessId");

                    b.HasOne("LenSys.Models.AppBusniessFinance.AppBusniessFinanceBusniess.AppBusniessFinanceBusniess", null)
                        .WithMany("busniessDocuments")
                        .HasForeignKey("AppBusniessFinanceBusniessBusniessId");

                    b.HasOne("LenSys.Models.AppDevelopmentFinance.AppDevelopmentFinanceBusniess.AppDevelopmentFinanceBusniess", null)
                        .WithMany("busniessDocuments")
                        .HasForeignKey("AppDevelopmentFinanceBusniessBusniessId");

                    b.HasOne("LenSys.Models.AppPropertyFinance.AppPropertyFinanceBusniess.AppPropertyFinanceBusniess", null)
                        .WithMany("busniessDocuments")
                        .HasForeignKey("AppPropertyFinanceBusniessBusniessId");
                });

            modelBuilder.Entity("LenSys.Models.IndividualPropertySchedule.PropertySchedule", b =>
                {
                    b.HasOne("LenSys.Models.AppAssetFinance.AppAssetFinanceIndividual.AppAssetFinanceIndividual", null)
                        .WithMany("propertySchedule")
                        .HasForeignKey("AppAssetFinanceIndividualIndividualId");

                    b.HasOne("LenSys.Models.AppBusniessFinance.AppBusniessFinanceIndividual.AppBusniessFinanceIndividual", null)
                        .WithMany("propertySchedule")
                        .HasForeignKey("AppBusniessFinanceIndividualIndividualId");

                    b.HasOne("LenSys.Models.AppDevelopmentFinance.AppDevelopmentFinanceIndividual.AppDevelopmentFinanceIndividual", null)
                        .WithMany("propertySchedule")
                        .HasForeignKey("AppDevelopmentFinanceIndividualIndividualId");

                    b.HasOne("LenSys.Models.AppPropertyFinance.AppPropertyFinanceIndividual.AppPropertyFinanceIndividual", null)
                        .WithMany("propertySchedule")
                        .HasForeignKey("AppPropertyFinanceIndividualIndividualId");
                });

            modelBuilder.Entity("LenSys.Models.IndividualUploadDocuments.IndividualDocuments", b =>
                {
                    b.HasOne("LenSys.Models.AppAssetFinance.AppAssetFinanceIndividual.AppAssetFinanceIndividual", null)
                        .WithMany("individualDocuments")
                        .HasForeignKey("AppAssetFinanceIndividualIndividualId");

                    b.HasOne("LenSys.Models.AppBusniessFinance.AppBusniessFinanceIndividual.AppBusniessFinanceIndividual", null)
                        .WithMany("individualDocuments")
                        .HasForeignKey("AppBusniessFinanceIndividualIndividualId");

                    b.HasOne("LenSys.Models.AppDevelopmentFinance.AppDevelopmentFinanceIndividual.AppDevelopmentFinanceIndividual", null)
                        .WithMany("individualDocuments")
                        .HasForeignKey("AppDevelopmentFinanceIndividualIndividualId");

                    b.HasOne("LenSys.Models.AppPropertyFinance.AppPropertyFinanceIndividual.AppPropertyFinanceIndividual", null)
                        .WithMany("individualDocuments")
                        .HasForeignKey("AppPropertyFinanceIndividualIndividualId");
                });

            modelBuilder.Entity("LenSys.Models.AppAssetFinance.AppAssetFinance", b =>
                {
                    b.Navigation("busniesses");

                    b.Navigation("individuals");
                });

            modelBuilder.Entity("LenSys.Models.AppAssetFinance.AppAssetFinanceBusniess.AppAssetFinanceBusniess", b =>
                {
                    b.Navigation("busniessDocuments");

                    b.Navigation("busniessLiabilities");

                    b.Navigation("keyPrincipals");

                    b.Navigation("serviceability");
                });

            modelBuilder.Entity("LenSys.Models.AppAssetFinance.AppAssetFinanceIndividual.AppAssetFinanceIndividual", b =>
                {
                    b.Navigation("individualDocuments");

                    b.Navigation("propertySchedule");
                });

            modelBuilder.Entity("LenSys.Models.AppBusniessFinance.AppBusniessFinance", b =>
                {
                    b.Navigation("busniesses");

                    b.Navigation("individuals");

                    b.Navigation("securityDetails");
                });

            modelBuilder.Entity("LenSys.Models.AppBusniessFinance.AppBusniessFinanceBusniess.AppBusniessFinanceBusniess", b =>
                {
                    b.Navigation("busniessDocuments");

                    b.Navigation("busniessLiabilities");

                    b.Navigation("keyPrincipals");

                    b.Navigation("serviceability");
                });

            modelBuilder.Entity("LenSys.Models.AppBusniessFinance.AppBusniessFinanceIndividual.AppBusniessFinanceIndividual", b =>
                {
                    b.Navigation("individualDocuments");

                    b.Navigation("propertySchedule");
                });

            modelBuilder.Entity("LenSys.Models.AppDevelopmentFinance.AppDevelopmentFinance", b =>
                {
                    b.Navigation("busniesses");

                    b.Navigation("individuals");

                    b.Navigation("securityDetails");
                });

            modelBuilder.Entity("LenSys.Models.AppDevelopmentFinance.AppDevelopmentFinanceBusniess.AppDevelopmentFinanceBusniess", b =>
                {
                    b.Navigation("busniessDocuments");

                    b.Navigation("busniessLiabilities");

                    b.Navigation("keyPrincipals");

                    b.Navigation("serviceability");
                });

            modelBuilder.Entity("LenSys.Models.AppDevelopmentFinance.AppDevelopmentFinanceIndividual.AppDevelopmentFinanceIndividual", b =>
                {
                    b.Navigation("individualDocuments");

                    b.Navigation("propertySchedule");
                });

            modelBuilder.Entity("LenSys.Models.AppPropertyFinance.AppPropertyFinance", b =>
                {
                    b.Navigation("busniesses");

                    b.Navigation("individuals");

                    b.Navigation("securityDetails");
                });

            modelBuilder.Entity("LenSys.Models.AppPropertyFinance.AppPropertyFinanceBusniess.AppPropertyFinanceBusniess", b =>
                {
                    b.Navigation("busniessDocuments");

                    b.Navigation("busniessLiabilities");

                    b.Navigation("keyPrincipals");

                    b.Navigation("serviceability");
                });

            modelBuilder.Entity("LenSys.Models.AppPropertyFinance.AppPropertyFinanceIndividual.AppPropertyFinanceIndividual", b =>
                {
                    b.Navigation("individualDocuments");

                    b.Navigation("propertySchedule");
                });
#pragma warning restore 612, 618
        }
    }
}
