// <auto-generated />
using System;
using LenSys.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LenSys.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LenSys.Models.AppAssetFinance.AppAssetFinance", b =>
                {
                    b.Property<int>("AssetFinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssetType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BalloonPayment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Deposit")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LeadId")
                        .HasColumnType("int");

                    b.Property<int>("LoanAmount")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PurchasePriceOfAssetValue")
                        .HasColumnType("int");

                    b.Property<string>("RepaymentTermMonths")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VATincluded")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssetFinId");

                    b.HasIndex("LeadId");

                    b.ToTable("AppAssetFinance");
                });

            modelBuilder.Entity("LenSys.Models.AppBusniessFinance.AppBusniessFinance", b =>
                {
                    b.Property<int>("BusniessFinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountantAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountantCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountantEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountantName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccountantPhoneNo")
                        .HasColumnType("int");

                    b.Property<int>("AmountOfFinance")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BrokerFee")
                        .HasColumnType("int");

                    b.Property<string>("EverLivedinThisProperty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FCA_RegulatedLoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LeadId")
                        .HasColumnType("int");

                    b.Property<int>("RepaymentTermMonths")
                        .HasColumnType("int");

                    b.Property<string>("SecurityOffered")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfFinance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WillApplicantOrFamilyMemOwn40PercentOfSecurityatmortgageTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BusniessFinId");

                    b.HasIndex("LeadId");

                    b.ToTable("AppBusniessFinance");
                });

            modelBuilder.Entity("LenSys.Models.AppBusniessFinance.AppBusniessFinanceSecurityDetails", b =>
                {
                    b.Property<int>("SecurityDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressForPropertyOfSecurity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AppBusniessFinanceBusniessFinId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegalChargeOverProperty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfPropertyOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OriginalPurchasePrice")
                        .HasColumnType("int");

                    b.Property<int>("PostCode")
                        .HasColumnType("int");

                    b.Property<string>("PropertyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyValue")
                        .HasColumnType("int");

                    b.Property<string>("SecondLineAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tenure")
                        .HasColumnType("int");

                    b.Property<int>("YearsRemainingOnLeaseIfLeaseHold")
                        .HasColumnType("int");

                    b.HasKey("SecurityDetailsId");

                    b.HasIndex("AppBusniessFinanceBusniessFinId");

                    b.ToTable("AppBusniessFinanceSecurityDetails");
                });

            modelBuilder.Entity("LenSys.Models.AppDevelopmentFinance.AppDevelopmentFinance", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Acquistion")
                        .HasColumnType("datetime2");

                    b.Property<int>("AmountOfExistingLoanToBe")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BuildingSignOff")
                        .HasColumnType("datetime2");

                    b.Property<int>("CIL")
                        .HasColumnType("int");

                    b.Property<int>("ConstructionCost")
                        .HasColumnType("int");

                    b.Property<int>("Demolition")
                        .HasColumnType("int");

                    b.Property<string>("DetailsOfBuildersContrators")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetailsOfPlainingPermission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ElectricInstallation")
                        .HasColumnType("int");

                    b.Property<int>("EstateAgentFees")
                        .HasColumnType("int");

                    b.Property<string>("EverLivedinThisProperty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExistStrategy")
                        .HasColumnType("int");

                    b.Property<string>("FCA_RegulatedLoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GasInstallation")
                        .HasColumnType("int");

                    b.Property<int>("GrossDevelopmentValue")
                        .HasColumnType("int");

                    b.Property<int>("Insert1")
                        .HasColumnType("int");

                    b.Property<int>("Insert2")
                        .HasColumnType("int");

                    b.Property<int>("Insert3")
                        .HasColumnType("int");

                    b.Property<int>("Insert4")
                        .HasColumnType("int");

                    b.Property<int>("Labour")
                        .HasColumnType("int");

                    b.Property<int>("LandScapingCost")
                        .HasColumnType("int");

                    b.Property<int?>("LeadId")
                        .HasColumnType("int");

                    b.Property<int>("LegalFees")
                        .HasColumnType("int");

                    b.Property<int>("LoanAmount")
                        .HasColumnType("int");

                    b.Property<int>("LoanTermMonths")
                        .HasColumnType("int");

                    b.Property<int>("MarketValueOfLand")
                        .HasColumnType("int");

                    b.Property<int>("MaterialsCost")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OtherCostFinance")
                        .HasColumnType("int");

                    b.Property<DateTime>("PlainingConditions")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PlainingPermission")
                        .HasColumnType("datetime2");

                    b.Property<int>("PurchasePrice")
                        .HasColumnType("int");

                    b.Property<DateTime>("SaleLetWholeBuilding")
                        .HasColumnType("datetime2");

                    b.Property<string>("SellingCosts_Insert1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellingCosts_Insert2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SellingCosts_LegalFees")
                        .HasColumnType("int");

                    b.Property<int>("SellingCosts_Total")
                        .HasColumnType("int");

                    b.Property<int>("SourceOfDeposit")
                        .HasColumnType("int");

                    b.Property<int>("StampDuty")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartConstruction")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TargetCompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalCosts")
                        .HasColumnType("int");

                    b.Property<int>("TotalDevelopmentCost")
                        .HasColumnType("int");

                    b.Property<int>("WaterInstallation")
                        .HasColumnType("int");

                    b.Property<string>("WillApplicantOrFamilyMemOwn40PercentOfSecurityatmortgageTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoanId");

                    b.HasIndex("LeadId");

                    b.ToTable("AppDevelopmentFinance");
                });

            modelBuilder.Entity("LenSys.Models.AppDevelopmentFinance.AppDevelopmentFinanceSecurityDetails", b =>
                {
                    b.Property<int>("SecurityDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressForPropertyOfSecurity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AppDevelopmentFinanceLoanId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionOfProperty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfPropertyOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostCode")
                        .HasColumnType("int");

                    b.Property<string>("PropertyCurrentUse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondLineAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tenure")
                        .HasColumnType("int");

                    b.Property<int>("YearsRemainingOnLeaseIfLeaseHold")
                        .HasColumnType("int");

                    b.HasKey("SecurityDetailsId");

                    b.HasIndex("AppDevelopmentFinanceLoanId");

                    b.ToTable("AppDevelopmentFinanceSecurityDetails");
                });

            modelBuilder.Entity("LenSys.Models.AppPropertyFinance.AppPropertyFinance", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountantAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountantCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountantEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountantName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccountantPhoneNo")
                        .HasColumnType("int");

                    b.Property<int>("BrokerFee")
                        .HasColumnType("int");

                    b.Property<string>("EverLivedinThisProperty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FCA_RegulatedLoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LeadId")
                        .HasColumnType("int");

                    b.Property<int>("LoanAmount")
                        .HasColumnType("int");

                    b.Property<string>("LoanPurpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RateType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RepaymentTermMonths")
                        .HasColumnType("int");

                    b.Property<string>("RepaymentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolicitorAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolicitorCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SolicitorDXnumber")
                        .HasColumnType("int");

                    b.Property<string>("SolicitorEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolicitorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SolicitorPhoneNo")
                        .HasColumnType("int");

                    b.Property<int>("SourceOfDeposit")
                        .HasColumnType("int");

                    b.Property<DateTime>("TargetCompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("WillApplicantOrFamilyMemOwn40PercentOfSecurityatmortgageTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoanId");

                    b.HasIndex("LeadId");

                    b.ToTable("AppPropertyFinance");
                });

            modelBuilder.Entity("LenSys.Models.AppPropertyFinance.AppPropertyFinanceSecurityDetails", b =>
                {
                    b.Property<int>("SecurityDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressForPropertyOfSecurity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlreadyOwned")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AppPropertyFinanceLoanId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HMO_MUFB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfPropertyOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OriginalPurchasePrice")
                        .HasColumnType("int");

                    b.Property<int>("PostCode")
                        .HasColumnType("int");

                    b.Property<string>("PropertyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyValue")
                        .HasColumnType("int");

                    b.Property<int>("Rent")
                        .HasColumnType("int");

                    b.Property<string>("SecondLineAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tenure")
                        .HasColumnType("int");

                    b.Property<string>("UseOfFunds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearsRemainingOnLeaseIfLeaseHold")
                        .HasColumnType("int");

                    b.HasKey("SecurityDetailsId");

                    b.HasIndex("AppPropertyFinanceLoanId");

                    b.ToTable("AppPropertyFinanceSecurityDetails");
                });

            modelBuilder.Entity("LenSys.Models.Home.Lead", b =>
                {
                    b.Property<int>("LeadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyBusniessName")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IntroducerName")
                        .HasColumnType("int");

                    b.Property<int>("LoanAmount")
                        .HasColumnType("int");

                    b.Property<string>("LoanPurpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNo")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeadId");

                    b.ToTable("Lead");
                });

            modelBuilder.Entity("LenSys.Models.AppAssetFinance.AppAssetFinance", b =>
                {
                    b.HasOne("LenSys.Models.Home.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("LenSys.Models.AppBusniessFinance.AppBusniessFinance", b =>
                {
                    b.HasOne("LenSys.Models.Home.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("LenSys.Models.AppBusniessFinance.AppBusniessFinanceSecurityDetails", b =>
                {
                    b.HasOne("LenSys.Models.AppBusniessFinance.AppBusniessFinance", null)
                        .WithMany("securityDetails")
                        .HasForeignKey("AppBusniessFinanceBusniessFinId");
                });

            modelBuilder.Entity("LenSys.Models.AppDevelopmentFinance.AppDevelopmentFinance", b =>
                {
                    b.HasOne("LenSys.Models.Home.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("LenSys.Models.AppDevelopmentFinance.AppDevelopmentFinanceSecurityDetails", b =>
                {
                    b.HasOne("LenSys.Models.AppDevelopmentFinance.AppDevelopmentFinance", null)
                        .WithMany("securityDetails")
                        .HasForeignKey("AppDevelopmentFinanceLoanId");
                });

            modelBuilder.Entity("LenSys.Models.AppPropertyFinance.AppPropertyFinance", b =>
                {
                    b.HasOne("LenSys.Models.Home.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("LenSys.Models.AppPropertyFinance.AppPropertyFinanceSecurityDetails", b =>
                {
                    b.HasOne("LenSys.Models.AppPropertyFinance.AppPropertyFinance", null)
                        .WithMany("securityDetails")
                        .HasForeignKey("AppPropertyFinanceLoanId");
                });

            modelBuilder.Entity("LenSys.Models.AppBusniessFinance.AppBusniessFinance", b =>
                {
                    b.Navigation("securityDetails");
                });

            modelBuilder.Entity("LenSys.Models.AppDevelopmentFinance.AppDevelopmentFinance", b =>
                {
                    b.Navigation("securityDetails");
                });

            modelBuilder.Entity("LenSys.Models.AppPropertyFinance.AppPropertyFinance", b =>
                {
                    b.Navigation("securityDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
